theme = "concise"

baseURL = "https://figueredo.co/"
title = "figueredo"

languageCode = "en"
language = "en"
enableInlineShortcodes = true

enableEmoji = true
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
enableRobotsTXT = true

[params]
  author = "Thiago Cardoso"
  profilePicture = "img/avatar.jpg"

  copyright = "Thiago Cardoso"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

  error404Message = "oops! page not found."
  error404Picture = "img/404.jpg"

  [[params.links]]
    title = "Twitter"
    url = "https://twitter.com/figueredo_"

  [[params.links]]
    title = "GitHub"
    url = "https://github.com/figueredo"

  [[params.links]]
    title = "LinkedIn"
    url = "https://linkedin.com/in/figueredo"

  [[params.links]]
    title = "DEV"
    url = "https://dev.to/figueredo"

  [[params.links]]
    title = "Medium"
    url = "https://medium.com/@figueredo_"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4