theme = "soho"

baseURL = "https://figueredo.co/"
title = "Thiago Cardoso"
languageCode = "en"
language = "en"
enableInlineShortcodes = true

summaryLength = 10
enableEmoji = true
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
enableRobotsTXT = true

[params]
  author = "Thiago Cardoso"
  profilePicture = "img/avatar.jpg"

  copyright = "Thiago Cardoso"
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

  themeColor = "#1f1f1f"
  error404 = "There is no such page."

  [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/figueredo"

  [[params.socialIcons]]
    icon = "fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/figueredo_"

  [[params.socialIcons]]
    icon = "fa-linkedin"
    title = "LinkedIn"
    url = "https://linkedin.com/in/figueredo"

  [[params.socialIcons]]
    icon = "fa-medium"
    title = "Medium"
    url = "https://medium.com/@figueredo_"

  [[params.socialIcons]]
    icon = "fa-dev"
    title = "DEV"
    url = "https://dev.to/figueredo"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4