theme = "concise"

title = "figueredo"
baseURL = "https://figueredo.co"

languageCode = "en"
language = "en"

enableInlineShortcodes = true
enableEmoji = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableRobotsTXT = true

googleAnalytics = "UA-179711502-1"

[params]
  author = "Thiago Cardoso"
  description = "Personal blog by Thiago Cardoso"

  error404Message = "oops! page not found."
  error404Picture = "/img/404.jpg"

  commentsTwitter = "figueredo_"

  [[params.links]]
    title = "Twitter"
    url = "https://twitter.com/figueredo_"

  [[params.links]]
    title = "GitHub"
    url = "https://github.com/figueredo"

  [[params.links]]
    title = "LinkedIn"
    url = "https://linkedin.com/in/figueredo"

  [[params.links]]
    title = "DEV"
    url = "https://dev.to/figueredo"

  [[params.links]]
    title = "Medium"
    url = "https://medium.com/@figueredo_"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4